// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { APINodeEdges } from "./APINodeEdges";

/**
 * A map of node IDs to their outgoing edges.
 */
export type APIEdges = { [key in number]?: APINodeEdges };
