// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WebMetadata } from "./WebMetadata";

export type APIMatch = {
  node_id: number;
  full_url: string;
  metadata: WebMetadata;
  insight: string | null;
  reason: string;
};
