// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { APINodeFlags } from "./APINodeFlags";
import type { APIPayload } from "./APIPayload";

export type APINodeItem = { id: number, labels: Array<string>, payload: APIPayload, flags: Array<APINodeFlags>, written_at: string, };
