// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { APINodeFlags } from "./APINodeFlags";
import type { APIPayload } from "./APIPayload";
import type { NodeLabel } from "./NodeLabel";

export type APINodeItem = {
  id: number;
  labels: Array<NodeLabel>;
  payload: APIPayload;
  flags: Array<APINodeFlags>;
  written_at: bigint;
};
