// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A list of all outgoing edges of a node, with the ID of the node and the label of the edge.
 * The UNIX timestamp represents when a node's edge list was last written to.
 */
export type APINodeEdges = {
  edges: Array<[number, string]>;
  written_at: bigint;
};
