// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Link } from "./Link";
import type { TableRow } from "./TableRow";
import type { WorkflowStep } from "./WorkflowStep";

export type APIPayload =
  | { type: "WorkflowStep"; data: WorkflowStep }
  | { type: "Link"; data: Link }
  | { type: "Text"; data: string }
  | { type: "Tree"; data: string }
  | { type: "TableRow"; data: TableRow };
