// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Classification } from "./Classification";
import type { ClassifierSettings } from "./ClassifierSettings";
import type { CrawlerSettings } from "./CrawlerSettings";
import type { EntityName } from "./EntityName";
import type { ExtractedEntity } from "./ExtractedEntity";
import type { Link } from "./Link";
import type { ProjectSettings } from "./ProjectSettings";
import type { TableRow } from "./TableRow";
import type { WebMetadata } from "./WebMetadata";

/**
 * All nodes contain a data payload.
 * APIPayload is the schema for this payload and contains the type of payload and the data.
 */
export type APIPayload =
  | { type: "Link"; data: Link }
  | { type: "WebMetadata"; data: WebMetadata }
  | { type: "Text"; data: string }
  | { type: "Tree"; data: string }
  | { type: "TableRow"; data: TableRow }
  | { type: "ProjectSettings"; data: ProjectSettings }
  | { type: "CrawlerSettings"; data: CrawlerSettings }
  | { type: "ClassifierSettings"; data: ClassifierSettings }
  | { type: "Classification"; data: Classification }
  | { type: "NamedEntitiesToExtract"; data: Array<EntityName> }
  | { type: "ExtractedNamedEntities"; data: Array<ExtractedEntity> };
