// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ClassifierSettings = {
  prompt_to_classify_content_as_relevant_to_objective_or_not: string | null;
};
