// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Classification = {
  is_relevant: boolean;
  reason: string;
  insight_if_classified_as_relevant: string | null;
};
