// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ClassifierSettings = {
  query_to_classify_content_as_relevant_or_irrelevant_to_objective:
    | string
    | null;
};
