// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CommonNodeLabels =
  | "AddedByUser"
  | "Domain"
  | "Link"
  | "RobotsTxt"
  | "WebPage"
  | "Title"
  | "Heading"
  | "Paragraph"
  | "BulletPoints"
  | "OrderedPoints"
  | "SearchTerm";
