// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Conclusion = {
    conclusion_to_objective_based_on_insights: string | null;
    // TODO: add more fields
};
