// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CrawlerSettings = {
  keywords_to_search_the_web_to_get_starting_urls: Array<string> | null;
  crawl_link_if_anchor_text_has_any_of_these_keywords: Array<string> | null;
};
