// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

import { ToolEnabled } from "./ToolEnabled";

export type CrawlerSettings = {
  is_enabled: ToolEnabled;
  keywords_to_get_accurate_results_from_web_search: Array<string> | null;
  crawl_link_if_anchor_text_has_any_of_these_keywords: Array<string> | null;
};
