// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EdgeLabel =
  | "RelatedTo"
  | "ParentOf"
  | "ChildOf"
  | "ContentOf"
  | "PathOf"
  | "OwnerOf"
  | "BelongsTo"
  | "Suggests"
  | "SuggestedFor"
  | "Classifies"
  | "ClassifiedFor";
