// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EdgeLabel } from "./EdgeLabel";

export type EdgeWrite = {
  node_ids: [number, number];
  edge_labels: [EdgeLabel, EdgeLabel];
};
