// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { APIEdges } from "./APIEdges";
import type { APIMatch } from "./APIMatch";
import type { APINodeItem } from "./APINodeItem";
import type { Explore } from "./Explore";

/**
 * Engine's response for an API request.
 *
 * API requests for a project are sent to its engine.
 * The engine responds with an `EngineResponsePayload`, which is directly passed on as
 * the API response.
 */
export type EngineResponsePayload =
  | { type: "NodeCreatedSuccessfully"; data: number }
  | { type: "EdgeCreatedSuccessfully" }
  | { type: "Nodes"; data: Array<APINodeItem> }
  | { type: "Edges"; data: APIEdges }
  | { type: "Labels"; data: Array<string> }
  | { type: "Matches"; data: Array<APIMatch> }
  | { type: "Explore"; data: Explore }
  | { type: "Error"; data: string };
