// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { APINodeItem } from "./APINodeItem";

export type EngineResponseResults = {
  nodes: Array<APINodeItem>;
  labels: Array<string>;
  edges: { [node_id: number]: Array<[number, string]> };
};
