// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EngineApiData } from "./EngineApiData";

export type EngineApiResponse =
  | { type: "Results"; data: EngineApiData }
  | { type: "Error"; data: string };
