// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EngineApiQueryType } from "./EngineApiQueryType";
import type { Node } from "./Node";

export type EngineApiData = {
  nodes: Array<Node>;
  query_type: EngineApiQueryType;
};
