// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Node } from "./Node";

export type EngineApiData = {
  nodes: Array<Node>;
  labels: Array<string>;
  node_ids_by_label: { [label: string]: Array<number> };
};
