// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeItem } from "./NodeItem";

export type EngineResponseResults = {
  nodes: Array<NodeItem>;
  labels: Array<string>;
  node_ids_by_label: { [label: string]: Array<number> };
};
