// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeWrite } from "./NodeWrite";

export type EngineRequest =
  | "GetLabels"
  | { GetNodesWithLabel: string }
  | { GetRelatedNodes: number }
  | { GetPartNodes: number }
  | { CreateNode: NodeWrite };
