// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { APIEdges } from "./APIEdges";
import type { APINodeItem } from "./APINodeItem";

/**
 * Schema for response to the `explore` API request.
 */
export type Explore = {
  nodes: Array<APINodeItem>;
  edges: APIEdges;
  sibling_nodes: Array<Array<number>>;
};
