// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Link = {
    path: string;
    query: string | null,
    favicon: string | null,
    thumbnail: string | null,
    title: string | null,
    description: string | null,
    published_date: string | null,
    last_modified: string | null,
    language: string | null,
 };
