// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LossyLocation = { latitude: number | null, longitude: number | null, address_line_1: string, address_line_2: string | null, city: string | null, state: string | null, postal_code: string | null, country: string, };
