// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WebPageMatch } from "./WebPageMatch";

export type Matches = { urls: Array<string>; web_pages: Array<WebPageMatch> };
