// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Metadata = {
    author: string | null;
    creator: string | null;
    description: string | null;
    favicon: string | null;
    image: string | null;
    language: string | null;
    locale: string | null;
    modified_time: string | null;
    published_time: string | null;
    site_name: string | null;
    tags: string[] | null;
    title: string | null;
    url: string | null;
}
