// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Payload } from "./Payload";

export type Node = {
  id: number;
  label: string;
  payload: Payload;
  parent_id: number | null;
  part_node_ids: Array<number>;
  related_node_ids: Array<number>;
  written_at: string;
};
