// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NodeLabel =
  | "AddedByUser"
  | "Content"
  | "Domain"
  | "Heading"
  | "Link"
  | "ListItem"
  | "Objective"
  | "OrderedPoints"
  | "Paragraph"
  | "Partial"
  | "RobotsTxt"
  | "SearchTerm"
  | "Title"
  | "UnorderedPoints"
  | "WebPage";
