// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Payload } from "./Payload";

export type Node = {
  id: number;
  labels: Array<string>;
  payload: Payload;
  edges: { [key in string]?: Array<number> };
  written_at: string;
};
