// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LinkWrite } from "./LinkWrite";

export type NodeWrite =
  | { Link: LinkWrite }
  | { SearchTerm: string }
  | { Objective: string };
