// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LinkWrite } from "./LinkWrite";
import type { SearchTerm } from "./SearchTerm";
import type { Topic } from "./Topic";

export type NodeWrite =
  | { Link: LinkWrite }
  | { SearchTerm: SearchTerm }
  | { Topic: Topic };
