// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BulletPoints } from "./BulletPoints";
import type { Domain } from "./Domain";
import type { Heading } from "./Heading";
import type { Link } from "./Link";
import type { OrderedPoints } from "./OrderedPoints";
import type { Paragraph } from "./Paragraph";
import type { Rule } from "./Rule";
import type { Table } from "./Table";
import type { TableRow } from "./TableRow";
import type { Title } from "./Title";
import type { WebPage } from "./WebPage";

export type Payload =
  | { Rule: Rule }
  | { Domain: Domain }
  | { Link: Link }
  | { FileHTML: WebPage }
  | { Title: Title }
  | { Heading: Heading }
  | { Paragraph: Paragraph }
  | { BulletPoints: BulletPoints }
  | { OrderedPoints: OrderedPoints }
  | { Table: Table }
  | { TableRow: TableRow }
  | { Label: string }
  | { NamedEntity: [string, string] };
