// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectOwner } from "./ProjectOwner";

export type Project = { uuid: string, name: string, description: string | null, owner: ProjectOwner, };
