// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProjectSettings = {
  only_extract_data_from_specified_links: boolean;
  only_crawl_direct_links_from_specified_links: boolean;
  only_crawl_within_domains_of_specified_links: boolean;
  monitor_links_for_changes: boolean;
};
