// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProjectSettings = {
  extract_data_only_from_specified_links: boolean;
  crawl_within_domains_of_specified_links: boolean;
  crawl_direct_links_from_specified_links: boolean;
};
