// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectOwner } from "./ProjectOwner";

export type Project = {
  /**
   * Project ID (UUID)
   */
  uuid: string;
  /**
   * Project name - this is assigned by AI
   */
  name: string | null;
  /**
   * Project description - currently unused
   */
  description: string | null;
  /**
   * Project owner - for future use, currently defaults to Myself
   */
  owner: ProjectOwner;
};
