// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuleCondition } from "./RuleCondition";

export type Rule = {
  applies_to: string;
  action: string;
  conditions: Array<RuleCondition>;
};
