// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SettingsIncompleteReason } from "./SettingsIncompleteReason";

export type SettingsStatus =
  | { Incomplete: Array<SettingsIncompleteReason> }
  | "Complete";
