// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Settings = {
  anthropicApiKey: string | null;
  ollamaHosts: Array<string> | null;
  ollamaPort: number | null;
  mqttBrokerHost: string | null;
  pathToStorageDir: string | null;
  currentProject: string | null;
};
