// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TableCellType } from "./TableCellType";

export type TableRow = Array<TableCellType>;
