// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WebPage = {
  contents: string;
  is_scraped: boolean;
  is_classified: boolean;
  is_extracted: boolean;
};
