// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkspaceUpdate = {
  name: string | null;
  description: string | null;
  anthropic_api_key: string | null;
  brave_search_api_key: string | null;
  sendgrid_api_key: string | null;
  sendgrid_sender_email: string | null;
  sendgrid_receiver_email: string | null;
};
