// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowCondition } from "./WorkflowCondition";
import type { WorkflowProcess } from "./WorkflowProcess";

export type WorkflowStep = {
  process: WorkflowProcess;
  conditions: WorkflowCondition;
};
