// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { APIProvider } from "./APIProvider";

export type Workspace = {
  uuid: string;
  name: string;
  description: string | null;
  apiKeys: { [key in APIProvider]?: string };
};
