export type TailwindClassKeyType =
  | "app"
  | "navBar"
  | "navBar.logo"
  | "navBar.icon"
  | "navBar.link"
  | "navBar.link.active"
  | "sideBar"
  | "sideBar.logo"
  | "sideBar.link"
  | "sideBar.link.active"
  | "sideBar.label"
  | "sideBar.label.active"
  | "mainContent"
  | "heading"
  | "form.label"
  | "text"
  | "textSoft"
  | "textSuccess"
  | "textInfo"
  | "textDanger"
  | "textMuted"
  | "textWarning"
  | "input"
  | "textArea"
  | "link"
  | "breadcrumb"
  | "breadcrumb.link"
  | "breadcrumb.link.last"
  | "tabs"
  | "tabs.link"
  | "button.default"
  | "button.cancel"
  | "button.secondary"
  | "button.success"
  | "button.muted"
  | "highlight";

export type TailwindClassesType = {
  [key in TailwindClassKeyType]: string;
};
