on:
  push:
    branches: ["main"]
    tags:
      - "v*"
    paths:
      - "admin/**"
      - ".github/workflows/main_admin.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "admin/**"
      - ".github/workflows/main_admin.yml"

concurrency:
  # Avoid old jobs overlapping with new ones
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  main_admin:
    name: Admin Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - name: Install Node.js for Admin
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
          cache-dependency-path: "./admin/pnpm-lock.yaml"

      - name: Install dependencies for Admin
        working-directory: "./admin"
        run: pnpm install --frozen-lockfile

      - name: Build Admin
        working-directory: "./admin"
        run: pnpm run build
      
      - name: Tar Gzip the admin build directory
        if: startsWith(github.ref, 'refs/tags/v')
        run: tar -czvf admin.tar.gz -C admin/dist .
      
      - name: Upload Admin build artifacts
        if: startsWith(github.ref, 'refs/tags/v')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: admin.tar.gz
          tag: ${{ github.ref }}
