on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  main_pixlieai:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: ${{ github.event.repository.name }}
            asset_name: ${{ github.event.repository.name }}-linux-amd64
          # - os: windows-latest
          #   artifact_name: ${{ github.event.repository.name }}.exe
          #   asset_name: ${{ github.event.repository.name }}-windows-amd64.exe
          # - os: macos-latest
          #   artifact_name: ${{ github.event.repository.name }}
          #   asset_name: ${{ github.event.repository.name }}-macos-amd64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test pixlieai_rs
        working-directory: "./pixlieai_rs"
        run: cargo test --verbose

      - name: Build release
        working-directory: "./pixlieai_rs"
        run: cargo build --release
