on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  main_pixlieai:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: cli
            asset_name: pixlieai-linux-amd64
          - os: macos-latest
            artifact_name: cli
            asset_name: pixlieai-macos-amd64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test pixlieai_rs
        working-directory: "./pixlieai_rs"
        run: cargo test --verbose

      - name: Build release
        working-directory: "./pixlieai_rs"
        run: cargo build --release
