on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  main_admin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Install Node.js for Admin
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
          cache-dependency-path: "./admin/pnpm-lock.yaml"

      - name: Install dependencies for Admin
        working-directory: "./admin"
        run: pnpm install --frozen-lockfile

      - name: Build Admin
        working-directory: "./admin"
        run: pnpm run build
