on:
  push:
    branches: ["main", "ci/macos-builds"]
    tags:
      - "v*"
    paths:
      - "pixlie_ai/**"
      - ".github/workflows/main_pixlie_ai.yml"
      - "admin/src/api_types/**"
  pull_request:
    branches: ["main"]
    paths:
      - "pixlie_ai/**"
      - ".github/workflows/main_pixlie_ai.yml"
      - "admin/src/api_types/**"

env:
  CARGO_TERM_COLOR: always

jobs:
  main_pixlie_ai:
    name: Pixlie AI
    strategy:
      matrix:
        include:
          # - os: ubuntu-latest
          #   artifact_name: cli
          #   asset_name: pixlie-linux-amd64
          - os: macos-latest
            artifact_name: cli
            asset_name: pixlie-macos-amd64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Homebrew cache
        if: matrix.os == 'macos-latest'
        uses: tecolicom/actions-use-homebrew-tools@v1
        with:
          tools: 'llvm rocksdb lld'
          verbose: true
      - name: Setup environment variables for MacOS
        if: matrix.os == 'macos-latest'
        run: |
          # brew install llvm rocksdb lld
          echo "export DYLD_FALLBACK_LIBRARY_PATH=/opt/homebrew/opt/llvm/lib" >> $GITHUB_ENV
          echo "export DYLD_LIBRARY_PATH=/opt/homebrew/opt/llvm/lib${DYLD_LIBRARY_PATH:+:$DYLD_LIBRARY_PATH}" >> $GITHUB_ENV
          echo "export PATH=/opt/homebrew/opt/llvm/bin:$PATH" >> $GITHUB_ENV
          echo "export LIBCLANG_PATH=/opt/homebrew/opt/llvm/lib" >> $GITHUB_ENV
          echo "export CC=/opt/homebrew/opt/llvm/bin/clang" >> $GITHUB_ENV
          echo "export CXX=/opt/homebrew/opt/llvm/bin/clang++" >> $GITHUB_ENV
          echo "export ROCKSDB_INCLUDE_DIR=/opt/homebrew/opt/rocksdb/include" >> $GITHUB_ENV
          echo "export ROCKSDB_LIB_DIR=/opt/homebrew/opt/rocksdb/lib" >> $GITHUB_ENV
          echo "export LD=/opt/homebrew/opt/lld/bin/ld64.lld" >> $GITHUB_ENV
          echo "export LDFLAGS=-fuse-ld=/opt/homebrew/opt/lld/bin/ld64.lld" >> $GITHUB_ENV
          echo "export AR=/opt/homebrew/opt/llvm/bin/llvm-ar" >> $GITHUB_ENV
          # TODO: For some reason, the libclang.dylib is not found by the linker.
          # So we create a symlink to the libclang.dylib in /usr/local/lib
          # This is a hack. There should be a better way to do this.
          sudo mkdir -pv /usr/local/lib
          sudo ln -s /opt/homebrew/opt/llvm/lib/libclang.dylib /usr/local/lib/libclang.dylib

      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.os }}
          workspaces: "pixlie_ai -> target"

      - name: Test pixlie_ai
        working-directory: "./pixlie_ai"
        run: cargo test --verbose

      - name: Build release
        working-directory: "./pixlie_ai"
        run: cargo build --release

      - name: Upload binaries to release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: pixlie_ai/target/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
          overwrite: true
