on:
  push:
    tags:
      - "v*"

jobs:
  release_admin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Tar Gzip the gliner directory
        run: tar -czvf gliner.tar.gz -C gliner .

      - name: Upload gliner to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: gliner.tar.gz
          tag: ${{ github.ref }}
