on:
  push:
    tags:
      - "v*"

jobs:
  release_admin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Install Node.js for admin
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
          cache-dependency-path: "./admin/pnpm-lock.yaml"

      - name: Install dependencies for admin
        working-directory: "./admin"
        run: pnpm install --frozen-lockfile

      - name: Build admin
        working-directory: "./admin"
        run: pnpm run build

      - name: Gzip the admin build directory
        run: tar -czvf admin.tar.gz ./admin/dist

      - name: Upload admin to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: admin.tar.gz
          tag: ${{ github.ref }}
